### ISSUE TITLE
A way to extend your library with javascript?

### ISSUE THREAD

**Issue by jmdelgadoh** [OcelotlStudio/cfdi-pdf#1]
Hola! Muy util tu libreria, exactamente lo que estaba buscando. Queria intentar extender un poco la funcionalidad para agregar mas opciones y hacerlo un poco mas customizable. hice un fork e intenté importar mi fork a mi proyecto para trabajar esas modificaciones en conjunto con mi proyecto, pero me di cuenta que todo esta programado en typescript, y el problema es que al hacer el fork pues no tengo el /dist folder.

La verdad no se usar typescript y soy algo novato en cuanto a contribuciones de open source todavia. No tengo un issue con tu libreria tal cual, pero queria saber si tienes alguna sugerencia o solucion, para poder trabajar con este proyecto como si fuera JS.

Ya me voy a poner a estudiar typescript y ver si asi puedo compilarlo y hacer modificaciones y extensiones de funcionalidad, pero cualquier sugerencia de como empezar es buena!

Te lo agradezco

**Comment by luffynando** [comment]
Es que realmente lo que agrega el typescript es que el código sea fuertemente tipado. Y realmente no veo beneficio el retirarlo, mas bien veo mas contras, por ejemplo al tener la base de typescript funciona bien tanto proyectos ts como js. Y evita errores aunque igual si lo que gustas es contribuir, desde tu base, puedo verificarlos y ajustarlos. Saludos
